import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class EmployeeService {
  employeeArray = [
    {
      Name: 'Aurora',
      Age: 53,
      Email: 'ante.blandit@disparturient.ca',
      'Date of joining': '10/06/2019',
      'Phone number': '1628101902299',
      Street: '493 Iaculis Rd.',
      City: 'Lewiston',
      Zip: '42591-180',
      Region: 'Maine',
      Country: 'Sudan',
      Info:
        'est. Nunc ullamcorper, velit in aliquet lobortis, nisi nibh lacinia',
      EmployeeID: 1,
    },
    {
      Name: 'Ila',
      Age: 37,
      Email: 'Sed.et@purus.edu',
      'Date of joining': '26/05/2019',
      'Phone number': '1686011935499',
      Street: '823 Varius Ave',
      City: 'Beaumaris',
      Zip: '55970-446',
      Region: 'Anglesey',
      Country: 'Saint Helena, Ascension and Tristan da Cunha',
      Info: 'pretium et, rutrum non, hendrerit id, ante. Nunc mauris sapien,',
      EmployeeID: 2,
    },
    {
      Name: 'Rose',
      Age: 26,
      Email: 'Suspendisse.commodo@tristiquepharetraQuisque.co.uk',
      'Date of joining': '21/09/2018',
      'Phone number': '1650033077399',
      Street: 'P.O. Box 376, 1901 Justo Rd.',
      City: 'Vienna',
      Zip: '82720',
      Region: 'Vienna',
      Country: 'Jersey',
      Info: 'ornare, libero at auctor ullamcorper, nisl arcu iaculis enim, sit',
      EmployeeID: 3,
    },
    {
      Name: 'Neville',
      Age: 21,
      Email: 'est@tinciduntnibh.edu',
      'Date of joining': '13/11/2017',
      'Phone number': '1652020117199',
      Street: '3855 Lacinia Ave',
      City: 'Ukkel',
      Zip: '60407',
      Region: 'Brussels Hoofdstedelijk Gewest',
      Country: 'Norway',
      Info: 'et, rutrum non, hendrerit id, ante. Nunc mauris sapien, cursus',
      EmployeeID: 4,
    },
    {
      Name: 'Mira',
      Age: 28,
      Email: 'dui@cursuseteros.org',
      'Date of joining': '08/10/2017',
      'Phone number': '1693030708899',
      Street: 'P.O. Box 156, 4690 Sollicitudin Ave',
      City: 'Dublin',
      Zip: 'E1Y 9C5',
      Region: 'Leinster',
      Country: 'Virgin Islands, British',
      Info: 'sem mollis dui, in sodales elit erat vitae risus. Duis',
      EmployeeID: 5,
    },
    {
      Name: 'Megan',
      Age: 40,
      Email: 'felis.adipiscing@nequesed.com',
      'Date of joining': '14/03/2018',
      'Phone number': '1615091544599',
      Street: '2618 Risus. Ave',
      City: 'Salon-de-Provence',
      Zip: '03901',
      Region: 'PR',
      Country: 'Zimbabwe',
      Info: 'sem ut dolor dapibus gravida. Aliquam tincidunt, nunc ac mattis',
      EmployeeID: 6,
    },
    {
      Name: 'Austin',
      Age: 53,
      Email: 'rutrum.eu@velitegestaslacinia.net',
      'Date of joining': '10/02/2019',
      'Phone number': '1676120251599',
      Street: 'Ap #863-6907 Vel, Rd.',
      City: 'Kapolei',
      Zip: '82-129',
      Region: 'Hawaii',
      Country: 'Bhutan',
      Info: 'mi. Aliquam gravida mauris ut mi. Duis risus odio, auctor',
      EmployeeID: 7,
    },
    {
      Name: 'Shea',
      Age: 56,
      Email: 'at.velit.Pellentesque@felisadipiscingfringilla.org',
      'Date of joining': '17/06/2018',
      'Phone number': '1629100357399',
      Street: '6545 Sed Street',
      City: 'Gap',
      Zip: '2152',
      Region: 'PR',
      Country: 'Tunisia',
      Info: 'id sapien. Cras dolor dolor, tempus non, lacinia at, iaculis',
      EmployeeID: 8,
    },
    {
      Name: 'Bert',
      Age: 43,
      Email: 'odio@Proindolor.edu',
      'Date of joining': '18/05/2018',
      'Phone number': '1602123086599',
      Street: 'Ap #941-2997 Tortor. St.',
      City: 'Minto',
      Zip: '647310',
      Region: 'ON',
      Country: 'Ireland',
      Info: 'Duis cursus, diam at pretium aliquet, metus urna convallis erat,',
      EmployeeID: 9,
    },
    {
      Name: 'Lamar',
      Age: 64,
      Email: 'Quisque.tincidunt@SuspendisseduiFusce.com',
      'Date of joining': '18/10/2017',
      'Phone number': '1665061376299',
      Street: '510 Ante. Av.',
      City: 'Skegness',
      Zip: '4220',
      Region: 'Lincolnshire',
      Country: 'Samoa',
      Info: 'mi tempor lorem, eget mollis lectus pede et risus. Quisque',
      EmployeeID: 10,
    },
    {
      Name: 'Kay',
      Age: 65,
      Email: 'vehicula.risus.Nulla@egestasSed.co.uk',
      'Date of joining': '31/01/2019',
      'Phone number': '1623121265199',
      Street: '5073 Cubilia Road',
      City: 'Estevan',
      Zip: '8887',
      Region: 'Saskatchewan',
      Country: 'Laos',
      Info: 'pede sagittis augue, eu tempor erat neque non quam. Pellentesque',
      EmployeeID: 11,
    },
    {
      Name: 'Blair',
      Age: 20,
      Email: 'fringilla@risusat.net',
      'Date of joining': '19/11/2017',
      'Phone number': '1602090174699',
      Street: 'Ap #533-7225 Neque Rd.',
      City: 'Ajaccio',
      Zip: '4202',
      Region: 'Corse',
      Country: 'United States',
      Info: 'in faucibus orci luctus et ultrices posuere cubilia Curae; Donec',
      EmployeeID: 12,
    },
    {
      Name: 'Stone',
      Age: 33,
      Email: 'aliquet@sagittisDuis.org',
      'Date of joining': '23/01/2019',
      'Phone number': '1691120873599',
      Street: '393-9389 Lacus. Rd.',
      City: 'Geertruidenberg',
      Zip: '49-566',
      Region: 'Noord Brabant',
      Country: 'Greece',
      Info:
        'nibh vulputate mauris sagittis placerat. Cras dictum ultricies ligula. Nullam',
      EmployeeID: 13,
    },
    {
      Name: 'Sara',
      Age: 26,
      Email: 'enim.Etiam.gravida@aauctor.ca',
      'Date of joining': '24/11/2018',
      'Phone number': '1695032347999',
      Street: '5728 Sed St.',
      City: 'Lonzee',
      Zip: '831773',
      Region: 'Namen',
      Country: 'Mexico',
      Info: 'ac mattis velit justo nec ante. Maecenas mi felis, adipiscing',
      EmployeeID: 14,
    },
    {
      Name: 'Brody',
      Age: 37,
      Email: 'sagittis.felis@gravidaPraesenteu.com',
      'Date of joining': '27/03/2019',
      'Phone number': '1662010887999',
      Street: '849-5028 Dolor, Road',
      City: 'Oudergem',
      Zip: '769776',
      Region: 'BU',
      Country: 'Western Sahara',
      Info: 'vitae sodales nisi magna sed dui. Fusce aliquam, enim nec',
      EmployeeID: 15,
    },
    {
      Name: 'Dylan',
      Age: 46,
      Email: 'iaculis.nec@mollis.net',
      'Date of joining': '06/06/2019',
      'Phone number': '1692080840799',
      Street: '2016 Ultrices Street',
      City: 'Brisbane',
      Zip: '91143',
      Region: 'Queensland',
      Country: 'Montenegro',
      Info:
        'suscipit, est ac facilisis facilisis, magna tellus faucibus leo, in',
      EmployeeID: 16,
    },
    {
      Name: 'Joseph',
      Age: 49,
      Email: 'Sed.malesuada@natoquepenatibus.net',
      'Date of joining': '07/01/2018',
      'Phone number': '1684041637099',
      Street: 'P.O. Box 555, 1346 Duis Ave',
      City: 'Vienna',
      Zip: 'T4A 1N3',
      Region: 'Wie',
      Country: 'Virgin Islands, United States',
      Info: 'habitant morbi tristique senectus et netus et malesuada fames ac',
      EmployeeID: 17,
    },
    {
      Name: 'Inez',
      Age: 46,
      Email: 'eu@egetmetusIn.co.uk',
      'Date of joining': '26/03/2018',
      'Phone number': '1662051033699',
      Street: '794 Posuere St.',
      City: 'Ribeirão Preto',
      Zip: '44368',
      Region: 'São Paulo',
      Country: 'Oman',
      Info:
        'dui, semper et, lacinia vitae, sodales at, velit. Pellentesque ultricies',
      EmployeeID: 18,
    },
    {
      Name: 'Grady',
      Age: 28,
      Email: 'Sed.auctor.odio@aliquet.net',
      'Date of joining': '14/06/2019',
      'Phone number': '1640111297399',
      Street: '1386 Iaculis Av.',
      City: 'Saint-Nazaire',
      Zip: '64212',
      Region: 'Pays de la Loire',
      Country: 'Congo, the Democratic Republic of the',
      Info:
        'fermentum vel, mauris. Integer sem elit, pharetra ut, pharetra sed,',
      EmployeeID: 19,
    },
    {
      Name: 'Quinn',
      Age: 51,
      Email: 'euismod.mauris@semvitaealiquam.net',
      'Date of joining': '30/08/2018',
      'Phone number': '1647060826999',
      Street: 'P.O. Box 900, 7039 Eu, Avenue',
      City: 'Butte',
      Zip: '19-709',
      Region: 'MT',
      Country: 'Guinea',
      Info:
        'parturient montes, nascetur ridiculus mus. Donec dignissim magna a tortor.',
      EmployeeID: 20,
    },
    {
      Name: 'Kay',
      Age: 18,
      Email: 'velit.in.aliquet@quamdignissim.co.uk',
      'Date of joining': '13/05/2019',
      'Phone number': '1669070438799',
      Street: 'P.O. Box 277, 9874 Litora Av.',
      City: 'Campagna',
      Zip: '804870',
      Region: 'Campania',
      Country: 'Anguilla',
      Info:
        'neque vitae semper egestas, urna justo faucibus lectus, a sollicitudin',
      EmployeeID: 21,
    },
    {
      Name: 'Elvis',
      Age: 24,
      Email: 'vitae.diam.Proin@ullamcorper.com',
      'Date of joining': '13/06/2018',
      'Phone number': '1617021266099',
      Street: '484-5692 Posuere St.',
      City: 'Istanbul',
      Zip: '594237',
      Region: 'Istanbul',
      Country: 'Saint Barthélemy',
      Info:
        'augue scelerisque mollis. Phasellus libero mauris, aliquam eu, accumsan sed,',
      EmployeeID: 22,
    },
    {
      Name: 'Marny',
      Age: 37,
      Email: 'metus.In.nec@at.ca',
      'Date of joining': '15/03/2019',
      'Phone number': '1644101053599',
      Street: 'Ap #424-8235 Non, Avenue',
      City: 'Istres',
      Zip: '70888',
      Region: 'PR',
      Country: 'Laos',
      Info: 'Aenean gravida nunc sed pede. Cum sociis natoque penatibus et',
      EmployeeID: 23,
    },
    {
      Name: 'Constance',
      Age: 60,
      Email: 'ante.dictum.mi@euismodet.com',
      'Date of joining': '01/01/2019',
      'Phone number': '1607040244199',
      Street: '155-3682 Urna Av.',
      City: 'Gontrode',
      Zip: '5153',
      Region: 'Oost-Vlaanderen',
      Country: 'Vanuatu',
      Info: 'vulputate, nisi sem semper erat, in consectetuer ipsum nunc id',
      EmployeeID: 24,
    },
    {
      Name: 'Daniel',
      Age: 61,
      Email: 'eu@erategettincidunt.co.uk',
      'Date of joining': '06/08/2018',
      'Phone number': '1696080747099',
      Street: '7874 Enim. Avenue',
      City: 'Muzaffarpur',
      Zip: '16772',
      Region: 'BR',
      Country: 'Haiti',
      Info: 'consequat enim diam vel arcu. Curabitur ut odio vel est',
      EmployeeID: 25,
    },
    {
      Name: 'Lewis',
      Age: 48,
      Email: 'dictum.eleifend@Proinnislsem.net',
      'Date of joining': '18/05/2018',
      'Phone number': '1681042190699',
      Street: '2042 Id Street',
      City: 'Bastia',
      Zip: '58285',
      Region: 'CO',
      Country: 'Guadeloupe',
      Info: 'ut nisi a odio semper cursus. Integer mollis. Integer tincidunt',
      EmployeeID: 26,
    },
    {
      Name: 'Malik',
      Age: 21,
      Email: 'mattis.semper@ultricesposuere.ca',
      'Date of joining': '09/02/2019',
      'Phone number': '1607020388399',
      Street: 'Ap #164-1035 Nisl St.',
      City: 'Castelluccio Valmaggiore',
      Zip: '43292',
      Region: 'PUG',
      Country: 'American Samoa',
      Info:
        'tristique neque venenatis lacus. Etiam bibendum fermentum metus. Aenean sed',
      EmployeeID: 27,
    },
    {
      Name: 'Laurel',
      Age: 31,
      Email: 'ornare.placerat.orci@Lorem.co.uk',
      'Date of joining': '31/01/2018',
      'Phone number': '1655080107399',
      Street: 'P.O. Box 285, 2529 Donec Ave',
      City: 'Zwolle',
      Zip: '6949 YR',
      Region: 'Overijssel',
      Country: 'Faroe Islands',
      Info: 'porta elit, a feugiat tellus lorem eu metus. In lorem.',
      EmployeeID: 28,
    },
    {
      Name: 'Beverly',
      Age: 20,
      Email: 'Nunc.mauris.sapien@ridiculusmus.net',
      'Date of joining': '04/11/2018',
      'Phone number': '1639072308799',
      Street: '336 Amet Avenue',
      City: 'Blois',
      Zip: '2018',
      Region: 'CE',
      Country: 'Jordan',
      Info: 'Sed diam lorem, auctor quis, tristique ac, eleifend vitae, erat.',
      EmployeeID: 29,
    },
    {
      Name: 'Jeremy',
      Age: 65,
      Email: 'cursus@semconsequatnec.com',
      'Date of joining': '21/04/2019',
      'Phone number': '1659030109999',
      Street: 'P.O. Box 396, 7893 Tempus Ave',
      City: 'Etobicoke',
      Zip: '76957',
      Region: 'Ontario',
      Country: 'Tunisia',
      Info: 'Donec est mauris, rhoncus id, mollis nec, cursus a, enim.',
      EmployeeID: 30,
    },
    {
      Name: 'Britanney',
      Age: 23,
      Email: 'nisi.dictum@nibh.net',
      'Date of joining': '14/03/2019',
      'Phone number': '1654022385599',
      Street: '336-9286 Semper Av.',
      City: 'Jönköping',
      Zip: '70680',
      Region: 'F',
      Country: 'Slovenia',
      Info:
        'non, dapibus rutrum, justo. Praesent luctus. Curabitur egestas nunc sed',
      EmployeeID: 31,
    },
    {
      Name: 'Rafael',
      Age: 18,
      Email: 'Aliquam@vestibulumnec.co.uk',
      'Date of joining': '06/04/2019',
      'Phone number': '1647101015499',
      Street: '8311 Ante St.',
      City: 'Brest',
      Zip: '82310',
      Region: 'Bretagne',
      Country: 'Belize',
      Info: 'varius et, euismod et, commodo at, libero. Morbi accumsan laoreet',
      EmployeeID: 32,
    },
    {
      Name: 'Russell',
      Age: 38,
      Email: 'metus.eu.erat@tacitisociosqu.ca',
      'Date of joining': '07/02/2019',
      'Phone number': '1648040503699',
      Street: 'Ap #138-3828 Quam Road',
      City: 'Le Petit-Quevilly',
      Zip: '8053',
      Region: 'HA',
      Country: 'Cuba',
      Info: 'Quisque libero lacus, varius et, euismod et, commodo at, libero.',
      EmployeeID: 33,
    },
    {
      Name: 'Igor',
      Age: 30,
      Email: 'diam.lorem@a.com',
      'Date of joining': '26/05/2018',
      'Phone number': '1692070373899',
      Street: 'P.O. Box 479, 9098 Molestie St.',
      City: 'Chalon-sur-Saône',
      Zip: '99803',
      Region: 'Bourgogne',
      Country: 'Austria',
      Info:
        'eu, eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur dictum.',
      EmployeeID: 34,
    },
    {
      Name: 'Unity',
      Age: 41,
      Email: 'et.netus@orciinconsequat.edu',
      'Date of joining': '16/11/2017',
      'Phone number': '1685061667299',
      Street: '2091 Elit Av.',
      City: 'Gdynia',
      Zip: '11519',
      Region: 'PM',
      Country: 'Gibraltar',
      Info: 'gravida nunc sed pede. Cum sociis natoque penatibus et magnis',
      EmployeeID: 35,
    },
    {
      Name: 'Zeph',
      Age: 57,
      Email: 'eget@vitae.net',
      'Date of joining': '05/11/2017',
      'Phone number': '1601081883799',
      Street: 'P.O. Box 249, 812 Amet Rd.',
      City: 'Huntsville',
      Zip: '398053',
      Region: 'Alabama',
      Country: 'United Arab Emirates',
      Info:
        'enim. Mauris quis turpis vitae purus gravida sagittis. Duis gravida.',
      EmployeeID: 36,
    },
    {
      Name: 'Zenaida',
      Age: 58,
      Email: 'ut.eros@utcursusluctus.co.uk',
      'Date of joining': '30/01/2018',
      'Phone number': '1622050676299',
      Street: '838-8536 Interdum St.',
      City: 'Vienna',
      Zip: '21319',
      Region: 'Wie',
      Country: 'Iran',
      Info:
        'facilisis lorem tristique aliquet. Phasellus fermentum convallis ligula. Donec luctus',
      EmployeeID: 37,
    },
    {
      Name: 'Dominic',
      Age: 52,
      Email: 'sodales.purus.in@nuncestmollis.net',
      'Date of joining': '15/10/2018',
      'Phone number': '1631062148099',
      Street: '9918 Sociis Rd.',
      City: 'Ipatinga',
      Zip: '63091',
      Region: 'MG',
      Country: 'Falkland Islands',
      Info:
        'augue malesuada malesuada. Integer id magna et ipsum cursus vestibulum.',
      EmployeeID: 38,
    },
    {
      Name: 'Illana',
      Age: 31,
      Email: 'auctor.vitae@sit.ca',
      'Date of joining': '30/12/2017',
      'Phone number': '1614070689899',
      Street: 'P.O. Box 655, 5601 Aliquet St.',
      City: 'Istanbul',
      Zip: '03514',
      Region: 'Istanbul',
      Country: 'Mauritania',
      Info: 'Quisque libero lacus, varius et, euismod et, commodo at, libero.',
      EmployeeID: 39,
    },
    {
      Name: 'Abra',
      Age: 66,
      Email: 'ipsum.cursus.vestibulum@sollicitudin.co.uk',
      'Date of joining': '08/07/2018',
      'Phone number': '1624042918699',
      Street: 'P.O. Box 741, 2747 In Street',
      City: 'Czestochowa',
      Zip: '84915',
      Region: 'Slaskie',
      Country: 'Lebanon',
      Info: 'ut mi. Duis risus odio, auctor vitae, aliquet nec, imperdiet',
      EmployeeID: 40,
    }
  ];
  selectedemployee = 0;

  constructor() {}

  getemployee(): any {
    // console.log('Selected EMployee : ' + this.selectedemployee);
    return this.employeeArray[this.selectedemployee];
  }
}
